name: User Build

on:
  workflow_dispatch:
  push:
    paths:
      - "app/boards/shields/supermini_macropad/**"
      - "app/boards/espressif/esp32c3_supermini/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build SuperMini Macropad
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install West
        run: pip install west

      - name: West Init
        run: west init -l app

      - name: West Update
        run: west update

      - name: West Zephyr Export
        run: west zephyr-export

      - name: Install Zephyr SDK
        run: |
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.5/zephyr-sdk-0.16.5_linux-x86_64_minimal.tar.xz
          tar xf zephyr-sdk-0.16.5_linux-x86_64_minimal.tar.xz
          cd zephyr-sdk-0.16.5
          ./setup.sh -t riscv64-zephyr-elf -h -c
          cd ..

      - name: Install Python Dependencies
        run: pip install -r zephyr/scripts/requirements.txt

      - name: Build Firmware
        run: |
          export ZEPHYR_SDK_INSTALL_DIR=$PWD/zephyr-sdk-0.16.5
          west build -b esp32c3_supermini -s app -- -DSHIELD=supermini_macropad

      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: supermini_macropad_firmware
          path: |
            build/zephyr/zmk.bin
            build/zephyr/zmk.elf
